INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('1', '1', 'Porción con piel', '../assets/pescados/atlantico/porcion-con-piel.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('2', '1', 'Porción sin piel', '../assets/pescados/atlantico/porcion-sin-piel.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('3', '1', 'Filete con piel', '../assets/pescados/atlantico/filete-con-piel.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('4', '1', 'Filete sin piel', '../assets/pescados/atlantico/filete-sin-piel.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('5', '1', 'Entero', '../assets/pescados/atlantico/entero-con-cabeza.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('6', '1', 'Entero sin cabeza', '../assets/pescados/atlantico/entero-sin-cabeza.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('7', '1', 'Bits & Pieces', '../assets/pescados/atlantico/bits-&-pieces.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('8', '1', 'Harasu', '../assets/pescados/atlantico/harasu.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('9', '1', 'Scrape Meat', '../assets/pescados/atlantico/scrape-meat.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('10', '2', 'Porción con piel', '../assets/pescados/coho/porcion-con-piel.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('11', '2', 'Porción sin piel', '../assets/pescados/coho/porcion-sin-piel.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('12', '2', 'Filete con piel', '../assets/pescados/coho/filete-con-piel.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('13', '2', 'Filete sin piel', '../assets/pescados/coho/filete-con-piel.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('14', '2', 'Entero', '../assets/pescados/coho/entero-con-cabeza.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('15', '2', 'Entero sin cabeza', '../assets/pescados/coho/entero-sin-cabeza.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('16', '2', 'Bits & Pieces', '../assets/pescados/coho/bits-&-pieces.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('17', '2', 'Harasu', '../assets/pescados/coho/harasu.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('18', '2', 'Scrape Meat', '../assets/pescados/coho/scrape-meat.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('19', '3', 'Entero', '../assets/pescados/jurel/entero-con-cabeza.png', '1', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('20', '3', 'Entero sin cabeza', '../assets/pescados/jurel/entero-sin-cabeza.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('21', '3', 'Entero sin cabeza y cola', '../assets/pescados/jurel/entero-sin-cabeza-y-cola.png', '0', '1');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('22', '3', 'Natural', '../assets/pescados/jurel/natural.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('23', '3', 'En tomate', '../assets/pescados/jurel/en-tomate.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('24', '3', 'Sin sal', '../assets/pescados/jurel/sin-sal.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('25', '3', 'En aceite', '../assets/pescados/jurel/en-aceite.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('26', '3', 'En tomate picante', '../assets/pescados/jurel/en-tomate-picante.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('27', '4', 'Natural', '../assets/pescados/atun/natural.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('28', '5', 'Enteros al natural', '../assets/moluscos/mejillones/enteros-natural.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('29', '5', 'Enteros en ajo y mantequilla', '../assets/moluscos/mejillones/enteros-ajo-y-mantequilla.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('30', '5', 'Enteros en tomate y ajo', '../assets/moluscos/mejillones/enteros-tomate-y-ajo.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('31', '5', 'Enteros en vino blanco', '../assets/moluscos/mejillones/enteros-vino-blanco.png', '0', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('32', '5', 'Enteros orgánico', '../assets/moluscos/mejillones/enteros-organico.png', '0', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('33', '5', 'Carne al natural', '../assets/moluscos/mejillones/carne-natural.png', '0', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('34', '5', 'Carne en salsa de ajo y mantequilla', '../assets/moluscos/mejillones/carne-ajo-y-mantequilla.png', '0', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('35', '6', 'Enteros crudos', '../assets/moluscos/abalones/enteros-crudos.png', '0', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('36', '6', 'Enteros precocidos', '../assets/moluscos/abalones/enteros-precocidos.png', '0', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('37', '6', 'Carne', '../assets/moluscos/abalones/carne.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('38', '6', 'Conserva', '../assets/moluscos/abalones/conserva.png', '1', '0');
INSERT INTO `test`.`products` (`id`, `id_subtype`, `product`, `img`, `cliente`, `proveedor`) VALUES ('39', '7', 'Cocidas', '../assets/crustaceos/langostinos/cocidas.png', '1', '0');
